// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYQ5bXHQ2m_urY4_8AziqeU14lR0ZQZWA',
    appId: '1:1054337998233:web:10bc5566f13a791cdc4708',
    messagingSenderId: '1054337998233',
    projectId: 'quizapp-20838',
    authDomain: 'quizapp-20838.firebaseapp.com',
    storageBucket: 'quizapp-20838.appspot.com',
    measurementId: 'G-SL7DF5D714',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7gzPQd4G93VLzKn0r3Uyb_vQnpr3YIs',
    appId: '1:1054337998233:android:fcfbe5a20314c07ddc4708',
    messagingSenderId: '1054337998233',
    projectId: 'quizapp-20838',
    storageBucket: 'quizapp-20838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXEKa_bOV2MyzJutTB9qHytrdb07Hl5fM',
    appId: '1:1054337998233:ios:a212380302301c99dc4708',
    messagingSenderId: '1054337998233',
    projectId: 'quizapp-20838',
    storageBucket: 'quizapp-20838.appspot.com',
    androidClientId: '1054337998233-akcdurelioqc82oc0u68g3opi0evnetd.apps.googleusercontent.com',
    iosClientId: '1054337998233-vsdtaq6mb3vu9tp21vn3kmltlnhqth69.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXEKa_bOV2MyzJutTB9qHytrdb07Hl5fM',
    appId: '1:1054337998233:ios:9c2c569cd0f0fb90dc4708',
    messagingSenderId: '1054337998233',
    projectId: 'quizapp-20838',
    storageBucket: 'quizapp-20838.appspot.com',
    androidClientId: '1054337998233-akcdurelioqc82oc0u68g3opi0evnetd.apps.googleusercontent.com',
    iosClientId: '1054337998233-20h7altr09j9q8gjt0jpbtacarqe3gha.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigations.RunnerTests',
  );
}
